language: node_js

node_js:
  - 10

cache:
  directories:
    - node_modules

script:
  - npm run build
  - npm test

after_success:
  - npm test -- --coverage

before_deploy:
  - npm run build

deploy:
  - provider: npm
    skip_cleanup: true
    email: info@inveniosoftware.org
    api_key:
      secure: iHRQ7ShL1HCKUrQQeWhnsFtuAehesloMnDBo8LdwSfhYrnbHT6FNCkdNDZAJhm8H2lwV/h2TKwp+Lj5HC+qkZzyh1wht2bBKjIGBgNi5K+4L9rbntfIGjP/QWIpax/gA6IfKxgqNYcsp5TsF28o4Th/x6XgNsN5R7PubMeGP0kxthD5VwcC6e1FsnyjMa9n8Ob73kat5XwhGPVTBpz2qu5HETseMiDHvdNgJijZREonuNrmKpaBbax6v98FHVP/qESgbr2PQMgWpx0fdvSpcIzzKmTsPC/VPaXWlyP7z2tVVwkSmJth1GLy5HCMZR8/SyRl8/tTWF/BScmTh8AJEOzrMjz21n+d9Tyz8WG50YuzrneWFZ/dQOfFJp7n0kHcapNtmzXpp/k0Ze3lOn1Z/Xu7jFngsfUcsA7lPuJYxco4wiX378HEsrY8rm0E37jwbuXc1T04DoHSIfUrSrQFHcL0upc5QrxZ759l6LYA2RJxEsbkBBc7OlvUPBiKGRlz3GEs42N4ioPvo8fFSLs/+NcxFQKh1yvjtiezv8GgZSbdZqR9GkYr0QzZ+fw0AHSeMzs52QJu1MzkEb2BEAj734rShc74EdoaCT/EVJ5n58w92Y3in7Rs8nR8JIPVn7mcKHQdQkO6rVrHoyI6IByt5sej2ECwMAF+2YfIWenJX1Qs=
    on:
      branch: master
      tags: true
      repo: inveniosoftware/react-invenio-forms
