name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  Tests:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Test
        run: npm test
